In [78]:
import numpy as np
import pandas as pd

In [79]:
# train dataset

train = pd.read_csv('C://Users//usama//Downloads//train.csv')
train.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [80]:
train.info()
print('\n\nSize of training set:')
train.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


Size of training set:


(4209, 378)

In [81]:
y_train = train['y'].values
y_train

array([130.81,  88.53,  76.26, ..., 109.22,  87.48, 110.85])

In [82]:
colums_x = [c for c in train.columns if 'X' in c]
# colums_x
print(len(colums_x))
print(train[colums_x].dtypes.value_counts())

376
int64     368
object      8
dtype: int64


In [119]:
# test dataset

test = pd.read_csv('C://Users//usama//Downloads//test.csv')
test.head()

ID  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  X380  \
0   1  az  v   n  f  d  t  a  w    0  ...     0     0     0     1     0     0   
1   2   t  b  ai  a  d  b  g  y    0  ...     0     0     1     0     0     0   
2   3  az  v  as  f  d  a  j  j    0  ...     0     0     0     1     0     0   
3   4  az  l   n  f  d  z  l  n    0  ...     0     0     0     1     0     0   
4   5   w  s  as  c  d  y  i  m    0  ...     1     0     0     0     0     0   

   X382  X383  X384  X385  
0     0     0     0     0  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 377 columns]

In [84]:
train.info()
print('\n\nSize of training set')
train.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


Size of training set


(4209, 378)

In [85]:
# Final dataset after removing ID 

final_column = list(set(train.columns) - set(['ID', 'y']))

x_train = train[final_column]
x_train
x_test = test[final_column]
x_test

X76  X150  X47  X369  X208  X320  X16  X15  X371  X55  ...  X246  X29  \
0       1     1    0     0     0     0    0    0     0    0  ...     1    1   
1       0     0    0     0     1     0    0    0     0    0  ...     0    0   
2       1     1    0     0     0     0    0    0     0    0  ...     0    1   
3       1     1    0     0     0     0    0    0     0    0  ...     1    1   
4       0     1    0     0     0     0    0    0     0    0  ...     1    0   
...   ...   ...  ...   ...   ...   ...  ...  ...   ...  ...  ...   ...  ...   
4204    0     1    0     0     0     0    0    0     0    0  ...     1    0   
4205    0     1    0     0     0     0    0    0     0    0  ...     0    0   
4206    0     1    0     0     0     0    0    0     0    0  ...     0    0   
4207    0     1    0     0     0     0    0    0     0    0  ...     1    0   
4208    0     0    0     0     0     0    0    0     0    0  ...     0    0   

      X33  X14  X220  X135  X148  X173  X147  X96  
0       0    0     1     0     1     0     0    1  
1       0    0     0     0     0     0     0    0  
2       0    1     0     0     0     0     0    1  
3       0    0     1     0     1     0     0    1  
4       0    1     1     0     0     0     0    1  
...   ...  ...   ...   ...   ...   ...   ...  ...  
4204    0    1     1     0     0     0     0    1  
4205    0    0     0     0     0     0     0    1  
4206    0    1     1     0     0     0     0    1  
4207    0    1     1     0     0     0     0    1  
4208    0    0     0     0     0     0     0    0  

[4209 rows x 376 columns]

In [86]:
# Check Null values

def detect(df):
    if df.isnull().any().any():
        print("Yes")
    else:
        print("No")

detect(x_train)
detect(x_test)

No
No


In [87]:
# Remove columns if variance is 0 

for column in final_column:
    check = len(np.unique(x_train[column]))
    if check == 1:
        x_train.drop(column, axis = 1) 
        x_test.drop(column, axis = 1)
    if check > 2: # Column is categorical; hence mapping to ordinal measure of value
        mapit = lambda x: sum([ord(digit) for digit in x])
        x_train[column] = x_train[column].apply(mapit)
        x_test[column] = x_test[column].apply(mapit)

x_train.head()


C:\Users\usama\AppData\Local\Temp/ipykernel_9172/3504830279.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[column] = x_train[column].apply(mapit)
C:\Users\usama\AppData\Local\Temp/ipykernel_9172/3504830279.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[column] = x_test[column].apply(mapit)


X76  X150  X47  X369  X208  X320  X16  X15  X371  X55  ...  X246  X29  X33  \
0    0     1    0     0     0     0    0    0     0    0  ...     0    0    0   
1    0     1    0     0     0     0    0    0     0    0  ...     0    0    0   
2    1     1    0     0     0     0    0    0     0    0  ...     1    1    0   
3    1     1    0     0     0     0    0    0     0    0  ...     1    1    0   
4    1     1    0     0     0     0    0    0     1    0  ...     1    1    0   

   X14  X220  X135  X148  X173  X147  X96  
0    0     1     0     0     0     0    0  
1    0     0     0     0     0     0    1  
2    0     1     0     1     0     0    1  
3    0     1     0     1     0     0    1  
4    0     1     0     1     0     0    1  

[5 rows x 376 columns]

In [112]:
# Label Encoder

from sklearn.preprocessing import LabelEncoder

In [113]:
le = LabelEncoder()
print(le)

LabelEncoder()


In [122]:
# for train set

train["X0"].unique()

array([32, 20, 40,  9, 36, 43, 31, 29, 39, 35, 19, 27, 44, 45,  7,  8, 10,
       46, 37, 15, 12, 42,  5,  0, 26,  6, 25, 13, 24,  1, 22, 14, 30, 38,
       21, 18, 23, 41,  4, 16, 34, 33, 17, 11,  3, 28,  2], dtype=int64)

In [98]:
train.dtypes

ID            int64
y           float64
X0           object
X1           object
X2           object
             ...   
X382          int64
X383          int64
X384          int64
X385          int64
(X1, X2)      int32
Length: 379, dtype: object

In [115]:
train["X0"] = le.fit_transform(train["X0"])

In [116]:
train.head()

ID       y  X0  X1  X2 X3 X4 X5 X6 X8  ...  X376  X377  X378  X379  X380  \
0   0  130.81  32  23  at  a  d  u  j  o  ...     0     1     0     0     0   
1   6   88.53  32  21  av  e  d  y  l  o  ...     0     0     0     0     0   
2   7   76.26  20  24   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  20  21   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  20  23   n  f  d  h  d  n  ...     0     0     0     0     0   

   X382  X383  X384  X385  (X1, X2)  
0     0     0     0     0        23  
1     0     0     0     0        21  
2     1     0     0     0        24  
3     0     0     0     0        21  
4     0     0     0     0        23  

[5 rows x 379 columns]

In [117]:
train.dtypes

ID            int64
y           float64
X0            int64
X1            int32
X2           object
             ...   
X382          int64
X383          int64
X384          int64
X385          int64
(X1, X2)      int32
Length: 379, dtype: object

In [123]:
# for test set

test["X0"].unique()

array(['az', 't', 'w', 'y', 'x', 'f', 'ap', 'o', 'ay', 'al', 'h', 'z',
       'aj', 'd', 'v', 'ak', 'ba', 'n', 'j', 's', 'af', 'ax', 'at', 'aq',
       'av', 'm', 'k', 'a', 'e', 'ai', 'i', 'ag', 'b', 'am', 'aw', 'as',
       'r', 'ao', 'u', 'l', 'c', 'ad', 'au', 'bc', 'g', 'an', 'ae', 'p',
       'bb'], dtype=object)

In [125]:
test["X0"] = le.fit_transform(test["X0"])

In [126]:
test.head()

ID  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  X380  \
0   1  21  v   n  f  d  t  a  w    0  ...     0     0     0     1     0     0   
1   2  42  b  ai  a  d  b  g  y    0  ...     0     0     1     0     0     0   
2   3  21  v  as  f  d  a  j  j    0  ...     0     0     0     1     0     0   
3   4  21  l   n  f  d  z  l  n    0  ...     0     0     0     1     0     0   
4   5  45  s  as  c  d  y  i  m    0  ...     1     0     0     0     0     0   

   X382  X383  X384  X385  
0     0     0     0     0  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 377 columns]

In [127]:
test["X0"].unique()

array([21, 42, 45, 47, 46, 29, 12, 38, 20,  8, 31, 48,  6, 27, 44,  7, 23,
       37, 33, 41,  3, 19, 15, 13, 17, 36, 34,  0, 28,  5, 32,  4, 22,  9,
       18, 14, 40, 11, 43, 35, 26,  1, 16, 25, 30, 10,  2, 39, 24])

In [105]:
# Perform dimensionality reduction

from sklearn.decomposition import PCA
n_comp = 12
pca = PCA(n_components = n_comp, random_state = 42)
pca_result_train = pca.fit_transform(x_train)
pca_result_test = pca.transform(x_test)
print(pca_result_train)
print(pca_result_test)

[[-49.08156207  -4.90948084 -17.25085325 ...   1.65805422   0.93307109
    1.67849631]
 [-48.94680383  -7.22674339 -13.7631947  ...  -0.21431604   0.10918977
    0.44953954]
 [ 92.62761708  31.9940341  -26.17503456 ...  -0.6219392    2.92587828
   -0.52735294]
 ...
 [ 89.47970814  20.44554421  48.11999819 ...  -1.27196478  -0.28714703
    2.00799158]
 [ 96.97110845  31.50977186  49.20059282 ...   0.14366455  -0.9800055
    0.99183323]
 [-17.21024322 -14.22166025  55.38091289 ...  -0.28904525  -0.31644192
    0.69146972]]
[[ 9.22615149e+01  3.29260839e+01 -3.01130736e+01 ... -4.11417089e-01
   3.62101196e+00 -1.20765987e+00]
 [-3.48622379e+01  6.87132606e+00 -3.74760829e+01 ...  6.09268011e-01
  -6.95814819e-01 -4.24925574e-01]
 [ 4.36560426e+01 -5.05939489e+01 -6.10591086e+01 ... -3.20459248e-01
   2.60148714e+00 -1.53762474e+00]
 ...
 [-2.52437784e+01 -2.63794193e+01  5.40742341e+01 ...  6.03527442e-01
   2.61454311e-02  3.67036987e-02]
 [ 4.53823778e+01 -6.38062446e+01  3.58666036e+0

In [106]:
# ML Model

import xgboost as xgb
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

# Splitting the data by 80/20
x_train, x_valid, y_train, y_valid = train_test_split(pca_result_train, y_train, test_size = 0.2, random_state = 42)

In [107]:
f_train = xgb.DMatrix(x_train, label = y_train)
f_valid = xgb.DMatrix(x_valid, label = y_valid)
f_test = xgb.DMatrix(x_test)
f_test = xgb.DMatrix(pca_result_test)


In [108]:
params = {}
params['objective'] = 'reg:linear'
params['eta'] = 0.02
params['max_depth'] = 4

In [109]:

# Predicting the score

def scorer(m, w):
    labels = w.get_label()
    return 'r2', r2_score(labels, m)

final_set = [(f_train, 'train'), (f_valid, 'valid')]

P = xgb.train(params, f_train, 1000, final_set, early_stopping_rounds=50, feval=scorer, maximize=True, verbose_eval=10)


[02:12:56] WARNING: c:\ci\xgboost-split_1638290375667\work\src\objective\regression_obj.cu:188: reg:linear is now deprecated in favor of reg:squarederror.
[0]	train-rmse:98.99695	train-r2:-59.49733	valid-rmse:98.88884	valid-r2:-61.82690
[10]	train-rmse:81.14410	train-r2:-39.64492	valid-rmse:81.07848	valid-r2:-41.23399
[20]	train-rmse:66.59753	train-r2:-26.37844	valid-rmse:66.55611	valid-r2:-27.45948
[30]	train-rmse:54.75785	train-r2:-17.50910	valid-rmse:54.73408	valid-r2:-18.24716
[40]	train-rmse:45.14008	train-r2:-11.57816	valid-rmse:45.13878	valid-r2:-12.09033
[50]	train-rmse:37.34669	train-r2:-7.60987	valid-rmse:37.35600	valid-r2:-7.96544
[60]	train-rmse:31.04961	train-r2:-4.95120	valid-rmse:31.08594	valid-r2:-5.20839
[70]	train-rmse:25.98398	train-r2:-3.16777	valid-rmse:26.03268	valid-r2:-3.35400
[80]	train-rmse:21.93871	train-r2:-1.97108	valid-rmse:21.99969	valid-r2:-2.10946
[90]	train-rmse:18.73534	train-r2:-1.16678	valid-rmse:18.81786	valid-r2:-1.27505
[100]	train-rmse:16.22450	

In [110]:
# Predicting on test set

p_test = P.predict(f_test)
p_test

array([ 79.82283 ,  96.440384,  81.46857 , ...,  98.44635 , 107.56838 ,
        95.22439 ], dtype=float32)

In [111]:
Predicted_Data = pd.DataFrame()
Predicted_Data['y'] = p_test
Predicted_Data.head()

y
0   79.822830
1   96.440384
2   81.468567
3   77.482124
4  109.704941